spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: springcloud-config-cy-dev
---
spring:
    profiles: test
    application:
        name: springcloud-config-cy-test