spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client   #该微服务的名字
    datasource:
        url: jdbc:mysql:///cloudDB01?serverTimezone=GMT
        username: root
        password: root
    thymeleaf:
        prefix: classpath:/templates/pages/
        suffix: .html
    task:
        execution:
            pool:
                core-size: 5
                max-size: 16
                queue-capacity: 100
                keep-alive: 30
                allow-core-thread-timeout: false
            thread-name-prefix: spring.async.task-  

mybatis:
    configuration:
        default-statement-timeout: 30
        map-underscore-to-camel-case: true
    mapper-locations:
    - classpath:/mapper/*/*.xml

eureka:
    client:   #服务端注册进eureka服务列表中
        service-url:
            defaultZone: http://localhost:7001/eureka/
    instance:
        instance-id: microservicecloud-config-dept-client    #修改服务status的名字
        prefer-ip-address: true    #访问路径可以显示IP